export const categories = [
  { "Paints & Mediums": ["Colors", "Mediums", "Varnish & Fixatives"] },
  {
    "Drawing & Illustrations": [
      "Pencils",
      "Pens",
      "Drawing Surface",
      "Drawing Ink",
      "Sharpeners",
      "Wax Crayons",
      "Soft Pastel",
    ],
  },
  {
    Surfaces: [
      "Drawing Board",
      "Canvas",
      "Papers & Pads",
      "Watercolour Pad",
      "Acrylic Pad",
      "Artist Pad",
      "Sketch Pad",
      "Notebooks",
      "Oil Painting Pad",
      "Drawing & Sketch Books",
    ],
  },
  {
    "Brushes & Tools": [
      "Paint Brushes",
      "Flat Brushes",
      "Filbert Brushes",
      "Mop Brushes",
      "Wash Brushes",
      "Fan Brushes",
      "Brush Pen",
      "Calligraphy Pen",
      "Palette Knife",
    ],
  },
  {
    "Art Accessories": [
      "Glue & Adhesive",
      "Masking",
      "Paperclips & Fasteners",
      "Tapes",
      "Rulers",
      "Scissors",
      "Cutters",
      "Sharpeners",
      "Staplers & Punches",
      "White-Board & Permanent Marker",
      "Easel Stands",
    ],
  },
  {
    Stationery: [
      "Pencils",
      "Pens",
      "Notebooks",
      "Eraser & Correction Pens",
      "Calculators",
      "Cutters & Tape Dispenser",
      "Folders & Filings",
      "Inks",
      "Paperclips & Fasteners",
      "Tapes",
      "Pen Stand & Organisers",
      "Stamps & Pads",
      "Staplers & Punches",
      "Sticky Notes, Memo",
      "Stationery Set",
      "Magnifier",
    ],
  },
  { Brands: ["A-C", "D-H", "I-P", "Q-Z"] },
];

export const topCategories = [
  "Paints & Mediums",
  "Drawing & Illustrations",
  "Surfaces",
  "Brushes & Tools",
  "Art Accessories",
  "Stationery",
  "Brands",
];
